#!/bin/bash
cd ..
patch -p1 < patch/patch-3.4.100-101
patch -p1 < patch/patch-3.4.101-102
patch -p1 < patch/patch-3.4.102-103
patch -p1 < patch/patch-3.4.103-104
patch -p1 < patch/patch-3.4.104-105
patch -p1 < patch/patch-3.4.105-106
patch -p1 < patch/patch-3.4.106-107
patch -p1 < patch/patch-3.4.107-108
patch -p1 < patch/patch-3.4.108-109
patch -p1 < patch/patch-3.4.109-110
patch -p1 < patch/patch-3.4.110-111
patch -p1 < patch/patch-3.4.111-112
